spring:
  datasource:
    mariadb:
      url: jdbc:mariadb://localhost:3306/app
      username: app
      password: secret
      driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
